name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Install
        run: npm i

      - name: Test
        run: npm run test

      - name: Start App
        run: pm2 restart app
